# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0003_auto_20170506_0154'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.AddField(
            model_name='course',
            name='img',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
    ]
