# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0005_auto_20170509_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
