# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-14 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0006_auto_20170509_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='coin',
            field=models.IntegerField(max_length=50),
        ),
    ]
